services:
    app:
        image: xanonymous/sherlock
        volumes:
            - sherlock:/sherlock
        networks:
            - sherlock
        ports:
            - "8080:8080"
        environment:
            - ADMIN_PASSWORD=sherlock


volumes:
    sherlock:

networks:
    sherlock:
